### ISSUE TITLE
Nixnote2 Not starting

### ISSUE THREAD

**Issue by racdamico** [baumgarr/Nixnote2#422]
Hi, I just reinstalled Nixnote2 and now is not starting. I'm getting this error:

```
[rodrigo@gns3vm nixnotegit]$ nixnote2 
/usr/bin/nixnote2: /usr/lib/libcurl.so.3: no version information available (required by /usr/bin/nixnote2)
/usr/bin/nixnote2: /usr/lib/libcurl.so.3: no version information available (required by /usr/lib/libpoppler.so.74)
DEBUG 2018-03-29 17:56:09.359 ( gui/shortcutkeys.cpp @ 246 ) Unable to open file for reading or file does not exist. 
DEBUG 2018-03-29 17:56:09.359 ( gui/shortcutkeys.cpp @ 246 ) Unable to open file for reading or file does not exist. 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_LoadNote" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_LoadNote" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_SaveNote" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_SaveNote" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_ImportKeep" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_ImportKeep" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_ImportDelete" 
ERROR 2018-03-29 17:56:09.379 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_ImportDelete" 
ERROR 2018-03-29 17:56:09.566 ( nixnote.cpp @ 3873 ) "Error loading Webcam plugin: " "Cannot load library /usr/lib/nixnote2/plugins/libwebcamplugin.so: (libopencv_core.so.3.3: cannot open shared object file: No such file or directory)" 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
free(): invalid pointer
/usr/local/bin/nixnote2: line 3: 19414 Aborted                 (core dumped) env "LD_PRELOAD=libcurl.so.3" /usr/bin/nixnote2
```
I tried googling this error but can't fix. At the ARCH AUR website people are with the same error.

Using Arch Linux.

Can you help me, please?

Thank you

**Comment by jeffkowalski** [comment]
I'm seeing the same errors, @racdamico, although I have not changed my nixnote since rebuilding it on 2017-12-17.  Perhaps there's a recently updated dependency that's affecting us both.
I use Linux Mint 18.3, and keep it updated frequently.  Nixnote was working for me a couple weeks ago (mid-March 2018), and I was curious to retry when I saw your note.

**Comment by jeffkowalski** [comment]
An hour or so ago, it wasn't working, but trying again, it launches without issue.  Perhaps try again?

**Comment by racdamico** [comment]
Hi @jeffkowalski , I tried to update, remove and them reinstall. Still no luck. I keep my distribution updated. There are other people with same problem and until now I couldn't find a solution.
Thanks for your updates

**Comment by ansulev** [comment]
Same problem here, because of the opencv version:
angel@arch:~ 
 $ pacman -Ss opencv
extra/opencv 3.4.1-2 [installed]
    Open Source Computer Vision Library

After rebuilding got this:
ERROR 2018-04-07 08:07:43.829 ( nixnote.cpp @ 3873 ) "Error loading Webcam plugin: " "Cannot load library /usr/lib/nixnote2/plugins/libwebcamplugin.so: (/usr/lib/nixnote2/plugins/libwebcamplugin.so: undefined symbol: _ZNK2cv12VideoCapture8isOpenedEv)"

**Comment by racdamico** [comment]
Which version the opencv should be, @ansulev ?

**Comment by ansulev** [comment]
@racdamico since the error is missing libopencv_core.so.3.3, and the current is libopencv_core.so.3.4, downgrading the opencv package should fix the problem:
https://archive.archlinux.org/packages/o/opencv/opencv-3.3.1-3-x86_64.pkg.tar.xz
I am aware that this will broke other packages on my system, so waiting for the dev to update the source.

**Comment by atwinkelman** [comment]
I don't believe an old version of opencv to be the problem causing the issue and subsequent core dump. nixnote2 runs on my desktop (running arch with aur/nixnote2 installed) with these same errors: 
````
$ nixnote2 
DEBUG 2018-04-16 16:59:23.931 ( gui/shortcutkeys.cpp @ 246 ) Unable to open file for reading or file does not exist. 
DEBUG 2018-04-16 16:59:23.931 ( gui/shortcutkeys.cpp @ 246 ) Unable to open file for reading or file does not exist. 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_LoadNote" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_LoadNote" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_SaveNote" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_SaveNote" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_ImportKeep" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_ImportKeep" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 55 ) "Script filename is blank. Disabling exit " "ExitPoint_ImportDelete" 
ERROR 2018-04-16 16:59:23.931 ( exits/exitmanager.cpp @ 67 ) "Script file doesn't exist or cannot be read. Disabling exit " "ExitPoint_ImportDelete" 
ERROR 2018-04-16 16:59:23.954 ( nixnote.cpp @ 3873 ) "Error loading Webcam plugin: " "Cannot load library /usr/lib/nixnote2/plugins/libwebcamplugin.so: (/usr/lib/nixnote2/plugins/libwebcamplugin.so: undefined symbol: _ZNK2cv12VideoCapture8isOpenedEv)" 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
````
and then the window comes up and nixnote runs fine. 

On my laptop, however, I get the same output as @racdamico. I did try backing the version of opencv to 3.3, as per @ansulev's comment but to no avail.

Are there any other logs or something I can provide to help diagnose this issue?

**Comment by racdamico** [comment]
Hi, I had installed opencv 3.3, but still no luck. Thanks anyway @ansulev 

@atwinkelman I really don't know. Maybe there is package that is not list as dependance and I don't have this package.

**Comment by ansulev** [comment]
Since I need this and the developer seems busy, will try to comment out the code starting from line 3873 @ nixnote.cpp to avoid loading this plugin and rebuild

**Comment by ansulev** [comment]
Update: After reinstalling Arch on brand new SSD, I didn't installed OpenCV package and NixNote2 runs OK. I don't know which package installed the OpenCV as dependency on my old installation ...

**Comment by sujaataarya** [comment]
In a sense, a workaround is in the AUR
https://aur.archlinux.org/packages/nixnote2/
In the comment Milos.Kozina
I rebuilt the program and it starts.

**Comment by sujaataarya** [comment]
@ Milos.Kozina - Thanks for the solution.
Yesterday I installed JDK10, then nixnote did not start.
The usual solutions did not help)
JDK did not delete, I need it.
But recompilation with a fix in the file nbrowserwindow.cpp, in line 207 helped, but I did not comment on the stock. So the compilation error turned out.
I chose false instead of true.
))) Error in the terminal was saved in the terminal
ERROR 2018-07-08 15:36:12.207 ( nixnote.cpp @ 3873 ) "Error loading Webcam plugin: " "Cannot load library /usr/lib/nixnote2/plugins/libwebcamplugin.so: (/usr/lib/nixnote2/plugins/libwebcamplugin.so: undefined symbol: _ZNK2cv12VideoCapture8isOpenedEv)"

However, the program works well, thank you!

**Comment by robert7** [comment]
As you maybe noticed, the original maintainer isn't available now.. It someway happened, that I took over.. There is updated version of the app ("[v.2.1](https://github.com/robert7/nixnote2/releases)") in [my fork](https://github.com/robert7/nixnote2). So far I did mainly stabilization/bugfixing and added few new features. 

I suggest try the latest AppImage version. It should work on most reasonably recent distributions.
