### ISSUE TITLE
Inline PDF display issue

### ISSUE THREAD

**Issue by qsman** [baumgarr/Nixnote2#475]
Hello,

I am not code-savvy, so I apologize if something may be missing in this description

I am seeing the following:
Some PDF's will display inline with no issue
Some PDFs  show as a screen "Missing Plugin"
Some PDFs show as a notebook icon with 0 bytes
Some PDFs show as a notebook with a size, double-clicking will open in external reader
Web/Windows client display as normal

Linux Mint 19, cinnamon desktop, installed from PPA
After the first round of troubleshooting, I went back to the homepage and installed all the various recommended libraries for Qt5. I then purged/reinstalled nixnote2

My logfile:
INFO  2019-03-05 19:08:10.650 src/main.cpp:287 NixNote 201901281531~2.1.3-c~ubuntu18.04.1, build at Jan 28 2019 at 15:31:50, with Qt 5.9.5 running on 5.9.5
INFO  2019-03-05 19:08:10.650 src/main.cpp:290 To get more detailed startup logging use --logLevel=1
INFO  2019-03-05 19:11:47.030 src/html/enmlformatter.cpp:344 enml-cleanup: ===== rebuilding note ENML
INFO  2019-03-05 19:11:47.035 src/html/enmlformatter.cpp:308 enml-cleanup: tidy DONE: diagnostics: "line 1 column 1 - Warning: missing <!DOCTYPE> declaration; line 1 column 44 - Warning: inserting missing 'title' element; line 1 column 236 - Warning: <object> attribute \"align\" not allowed for XHTML5; line 1 column 236 - Warning: <object> proprietary attribute \"hash\"; line 1 column 236 - Warning: <object> proprietary attribute \"lid\"; Info: Document content looks like XHTML5; Tidy found 5 warnings and 0 errors!; ; "
WARN  2019-03-05 19:11:47.037 src/html/enmlformatter.cpp:879 enml-cleanup: checkAttributes - tag "object" removing invalid attribute "align"
WARN  2019-03-05 19:11:47.038 src/html/enmlformatter.cpp:879 enml-cleanup: checkAttributes - tag "object" removing invalid attribute "border"
WARN  2019-03-05 19:11:47.038 src/html/enmlformatter.cpp:814 enml-cleanup: removeInvalidAttributes - tag "object" removing  invalid attribute "lid"
INFO  2019-03-05 19:11:47.039 src/html/enmlformatter.cpp:308 enml-cleanup: tidy DONE: diagnostics: "line 1 column 1 - Warning: missing <!DOCTYPE> declaration; line 1 column 44 - Warning: inserting missing 'title' element; Info: Document content looks like XHTML5; Tidy found 2 warnings and 0 errors!; ; "
INFO  2019-03-05 19:11:47.039 src/html/enmlformatter.cpp:443 enml-cleanup: ===== finished rebuilding note ENML
ERROR 2019-03-05 19:23:11.721 src/communication/communicationmanager.cpp:513 Exception stacktrace:
ERROR 2019-03-05 19:23:11.724 src/communication/communicationerror.cpp:86 "EDAMUserException[BAD_DATA_FORMAT]: EDAMUserException: BAD_DATA_FORMAT parameter=Note.guid"

**Comment by robert7** [comment]
Hi,
this should be already fixed in v2.1 - try https://github.com/robert7/nixnote2/releases

**Comment by qsman** [comment]
Just downloaded 2.1.3 via  PPA - still not working correctly.

**Comment by robert7** [comment]
Hi,
I'm normally not using the "PDF inline display" myself... so I don't have much experience. But now I did few tests with few PDF and its working fine. So I'm not able to reproduce.
You need to provide some steps for reproduction... maybe some example PDFs, maybe log file (preferably with DEBUG level). Also preferably open issue in my fork.
