### ISSUE TITLE
Migrating to Qt5: "Cannot create children for a parent that is in a different thread."

### ISSUE THREAD

**Issue by michaelcadilhac** [baumgarr/Nixnote2#73]
Hi there;

I tried migrating Nixnote2 to Qt5, which, as a matter of fact, is my first attempt at doing anything Qt.  Making the whole project compile was not hard[1], but well, Nixnote does not work anymore.  The recurring error is of the form:
`Cannot create children for a parent that is in a different thread.`
and the shared objects (especially the resource table) is not populated (see: http://michael.cadilhac.name/public/nixnote-qt5-log.txt created with TRACE and starting from a fresh configuration, doing a sync).

Is there anyone with the proper set of skills who would be able to help me migrating Nixnote2?

[1]: See http://michael.cadilhac.name/public/nixnote-qt5.diff .

**Comment by baumgarr** [comment]
I haven't tried too seriously about migrating to Qt5 because I get into
issues with people running older distros.  The message for "children in a
different thread" happens in 4.8, so I wouldn't concentrate too seriously
on that message.

I don't see anything in the log file that concerns me.  I'd try to install
sqlite3 and see if the actual tables are being populated.  It looks like
the data is being retrieved so I'm guessing there is a problem with the SQL
logic that is causing the problem.

**Comment by michaelcadilhac** [comment]
So you'd say that the:
` Attempting to delete non-existing resource:  8 `
errors relate to the populating of the SQLite database rather than of the internal structures?  The net result of this Sync operation is that I see on the left column the number of notes, but the note list stays blank.  Is there any backtrace I can provide you with to help you?  Note that without my patch qt4→qt5, everything seems to work.

Cheers.

**Comment by baumgarr** [comment]
No.  The "attempting to delete non-existing resource" is normal.  When you do a sync & get a note NN will delete the local copy of the note & re-add it.  If it is a new note that it doesn't have locally it can't delete it.  That message is really there because I was having a different issue and I was trying to track it down.  You can ignore it.

The easiest way to narrow it down is to use sqlite3 to look at the DB in ~/.nixnote/db-1/nixnote.db.  Issue the query "select count(*) from notetable".  If it has a non-zero count then you have a problem with the gui or the filter.  If it is zero then the problem is that the SQL insert into that table is failing for some reason.

**Comment by michaelcadilhac** [comment]
1. The select count returns a nonzero number.
2. I can confirm that it is entirely unrelated to the messages I see.  In particular, using export QT_FATAL_WARNINGS=1 and gdb, I tracked down the following:

a) I had one warning about adding empty stuff to some list.  This was harmless and solved by:

```patch
diff --git a/watcher/filewatcher.cpp b/watcher/filewatcher.cpp
index 1967a6e..48bd350 100644
--- a/watcher/filewatcher.cpp
+++ b/watcher/filewatcher.cpp
@@ -193,13 +193,14 @@ void FileWatcher::addDirectory(QString root) {
     QStringList files;
     if (includeSubdirectories) {
         setupSubDirectories(dirs, files, root);
-        addPaths(dirs);
-        addPaths(files);
+        if (!dirs.isEmpty())
+	  addPaths(dirs);
     } else {
         setupDirectory(files, root);
         addPath(root);
-        addPaths(files);
     }
+    if (!files.isEmpty())
+      addPaths(files);
     if (scanType == ImportDelete) {
         for (int i=0; i<files.size(); i++) {
             saveFile(files[i]);
```

b) The QObject errors are due to `SyncRunner` being moved to another thread.  The NetworkAccessManager of `evernoteNetworkAccessManager` then does not live in the correct thread.  I don't think it is QEverCloud's fault, but that some more signals/slots should be used in Nixnote's code.  For what it's worth, deleting all the `moveToThread`s in `nixnote.cpp` gets rid of the warnings.

**Comment by michaelcadilhac** [comment]
Found the bug: somehow, boolean values are not converted to "true" or "false" when using `bindValue`, but to 1 or 0 (which is arguably a better behavior).  Not sure what would be your favorite way to ensure it works, though, but I went with replacing all occurrences of 'true' and 'false' to their values.

Attachment do not appear in the notes, but he, that's a good step.

**Comment by michaelcadilhac** [comment]
You have an awful lot of mix ups between SQL prepared queries and their `bindValue`s.  This function is now case-sensitive, and you have a couple of `:noteLid` in `resourcetable.cpp` that are substituted with `:notelid`.  Also, in `filterengine.cpp:81` you are binding the wrong value (i.e., not `:key`), same in `resourcetable:758` with `:hash`, `sharenotebooktable.cpp:378` and lines 399, 424, `resourcetable.cpp:146`, ... I mean at this point, it should be better to write a script :-)  Fixing all of these allows the attachments to be displayed.

**Comment by michaelcadilhac** [comment]
A very crude such script can be found here:  http://michael.cadilhac.name/private/checksql.sh .  Not sure if it catches them all, and sure it has false positives, but that's a good start.

**Comment by baumgarr** [comment]
I've added the same checks in FileWatcher and corrected the resourcetable.cpp.  Both have been pushed out.

I'll need to think of the easiest way to correct the case sensitive issue.  It may be easier to override the prepare & bindValue parameters in NSqlQuery to just uppercase (or lowercase) the statements, then just pass them on to QSqlQuery.

**Comment by michaelcadilhac** [comment]
The issue is not restricted to cased sensitivity, at all.  There are, throughout the code, instances of `prepare`/`bindValue` pairs that do not match.  One of my previous bug reports, on the unability to remove some tag or so, is probably entirely caused by these mismatches.  I took the extra step to fix every such typos reported by my script, above, leading to the following patch.  Note that there is still `FilterEngine::filterSearchStringAll` that I don't know how to fix.  It may be a good idea to equip `NSqlQuery` with a check that a query `exec`uted has all its variables bound.

```patch
diff --git a/filters/filterengine.cpp b/filters/filterengine.cpp
index 467df9e..850ac13 100644
--- a/filters/filterengine.cpp
+++ b/filters/filterengine.cpp
@@ -79,7 +79,7 @@ void FilterEngine::filter(FilterCriteria *newCriteria, QList<qint32> *results) {
 
     // Now, re-insert any pinned notes
     sql.prepare("Insert into filter (lid) select lid from Datastore where key=:key and lid not in (select lid from filter)");
-    sql.bindValue(":closedNotebooks", NOTE_ISPINNED);
+    sql.bindValue(":key", NOTE_ISPINNED);
     sql.exec();
 
 
@@ -356,16 +356,16 @@ void FilterEngine::filterAttributes(FilterCriteria *criteria) {
         sql.bindValue(":encryptedkey", NOTE_HAS_ENCRYPT);
         break;
     case CONTAINS_TODO_ITEMS:
-        sql.prepare("Delete from filter where lid not in (select lid from DataStore where (key=:comp or key=:uncomp) and data='true')");
+        sql.prepare("Delete from filter where lid not in (select lid from DataStore where (key=:comp or key=:uncomp) and data=1)");
         sql.bindValue(":comp", NOTE_HAS_TODO_COMPLETED);
         sql.bindValue(":uncomp", NOTE_HAS_TODO_UNCOMPLETED);
         break;
     case CONTAINS_FINISHED_TODO_ITEMS:
-        sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:comp and data='true')");
+        sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:comp and data=1)");
         sql.bindValue(":comp", NOTE_HAS_TODO_COMPLETED);
         break;
     case CONTAINS_UNFINISHED_TODO_ITEMS:
-        sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:uncomp and data='true')");
+        sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:uncomp and data=1)");
         sql.bindValue(":uncomp", NOTE_HAS_TODO_UNCOMPLETED);
         break;
     case CONTAINS_PDF_DOCUMENT:
@@ -563,7 +563,7 @@ void FilterEngine::filterTrash(FilterCriteria *criteria) {
             || (criteria->isDeletedOnlySet() && !criteria->getDeletedOnly()))
     {
         NSqlQuery sql(global.db);
-        sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:type and data='true')");
+        sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:type and data=1)");
         sql.bindValue(":type", NOTE_ACTIVE);
         sql.exec();
         sql.finish();
@@ -574,7 +574,7 @@ void FilterEngine::filterTrash(FilterCriteria *criteria) {
 
     // Filter out the records
     NSqlQuery sql(global.db);
-    sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:type and data='false')");
+    sql.prepare("Delete from filter where lid not in (select lid from DataStore where key=:type and data=0)");
     sql.bindValue(":type", NOTE_ACTIVE);
     sql.exec();
     sql.finish();
@@ -671,10 +671,12 @@ void FilterEngine::filterSearchStringAll(QStringList list) {
 
     sql.bindValue(":weight", global.getMinimumRecognitionWeight());
     sql.bindValue(":weight2", global.getMinimumRecognitionWeight());
+    // FIXME: THIS IS NOT USED
     sql.bindValue(":key", RESOURCE_NOTE_LID);
 
     sqlnegative.bindValue(":weight", global.getMinimumRecognitionWeight());
     sqlnegative.bindValue(":weight2", global.getMinimumRecognitionWeight());
+    // FIXME: THIS IS NOT USED
     sqlnegative.bindValue(":key2", RESOURCE_NOTE_LID);
 
     for (qint32 i=0; i<list.size(); i++) {
@@ -781,7 +783,7 @@ void FilterEngine::filterSearchStringIntitleAll(QString string) {
             string = QString("%") +string +QString("%");
         tagSql.prepare("Delete from filter where lid not in (select lid from datastore where key=:key and data like :title)");
         tagSql.bindValue(":key", NOTE_TITLE);
-        tagSql.bindValue(":data", string);
+        tagSql.bindValue(":title", string);
 
         tagSql.exec();
         tagSql.finish();
@@ -794,7 +796,7 @@ void FilterEngine::filterSearchStringIntitleAll(QString string) {
         string = string.replace("*", "%");
         if (string.indexOf("%") < 0)
             string = QString("%") +string +QString("%");
-        tagSql.prepare("Delete from filter where lid in (select lid from datastore where key=:key and data like :title)");
+        tagSql.prepare("Delete from filter where lid in (select lid from datastore where key=:key and data like :data)");
         tagSql.bindValue(":key", NOTE_TITLE);
         tagSql.bindValue(":data", string);
 
@@ -1660,7 +1662,7 @@ void FilterEngine::filterSearchStringIntitleAny(QString string) {
             string = QString("%") +string +QString("%");
         tagSql.prepare("insert into anylidsfilter (lid) select lid from datastore where key=:key and data like :title");
         tagSql.bindValue(":key", NOTE_TITLE);
-        tagSql.bindValue(":data", string);
+        tagSql.bindValue(":title", string);
 
         tagSql.exec();
         tagSql.finish();
@@ -1676,7 +1678,7 @@ void FilterEngine::filterSearchStringIntitleAny(QString string) {
             string = QString("%") +string +QString("%");
         tagSql.prepare("insert into anylidsfilter (lid) select lid from datastore where lid not in (select lid from datastore where key=:key and data like :title)");
         tagSql.bindValue(":key", NOTE_TITLE);
-        tagSql.bindValue(":data", string);
+        tagSql.bindValue(":title", string);
 
         tagSql.exec();
         tagSql.finish();
--- a/sql/favoritestable.cpp
+++ b/sql/favoritestable.cpp
@@ -170,7 +170,7 @@ void FavoritesTable::setOrder(QList< QPair< qint32, qint32 > > order) {
     for (int i=0; i<order.size(); i++) {
         query.bindValue(":lid", order[i].first);
         query.bindValue(":key", FAVORITES_ORDER);
-        query.bindValue(":data", order[i].second);
+        query.bindValue(":value", order[i].second);
         query.exec();
     }
     query.finish();
@@ -185,7 +185,7 @@ void FavoritesTable::expunge(qint32 lid) {
     NSqlQuery query(db);
     db->lockForWrite();
     query.prepare("delete from datastore where lid=:key");
-    query.bindValue(":lid", lid);
+    query.bindValue(":key", lid);
     query.exec();
     query.finish();
     db->unlock();
@@ -214,7 +214,7 @@ qint32 FavoritesTable::getLidByTarget(const QVariant &target) {
 qint32 FavoritesTable::add(const FavoritesRecord &record) {
     NSqlQuery query(db);
     db->lockForWrite();
-    query.prepare("Insert into datastore (lid, key, data) values (:lid, :key, :value)");
+    query.prepare("Insert into datastore (lid, key, data) values (:lid, :key, :data)");
 
     qint32 lid = record.lid;
     ConfigStore cs(db);
diff --git a/sql/linkednotebooktable.cpp b/sql/linkednotebooktable.cpp
index 7b27aab..f1106dc 100644
--- a/sql/linkednotebooktable.cpp
+++ b/sql/linkednotebooktable.cpp
@@ -471,7 +471,7 @@ void LinkedNotebookTable::renameStack(QString oldName, QString newName) {
     query.prepare("Update Datastore set data=:newname where key=:key and data=:oldname");
     query.bindValue(":newname", newName);
     query.bindValue(":key", LINKEDNOTEBOOK_STACK);
-    query.bindValue(":oldName", oldName);
+    query.bindValue(":oldname", oldName);
     query.exec();
     query.finish();
     db->unlock();
diff --git a/sql/notebooktable.cpp b/sql/notebooktable.cpp
index c6d99b7..0f0fc49 100644
--- a/sql/notebooktable.cpp
+++ b/sql/notebooktable.cpp
@@ -754,7 +754,7 @@ void NotebookTable::renameStack(QString oldName, QString newName) {
     query.prepare("Update Datastore set data=:newname where key=:key and data=:oldname");
     query.bindValue(":newname", newName);
     query.bindValue(":key", NOTEBOOK_STACK);
-    query.bindValue(":oldName", oldName);
+    query.bindValue(":oldname", oldName);
     query.exec();
     query.finish();
     db->unlock();
@@ -855,7 +855,7 @@ qint32 NotebookTable::getDefaultNotebookLid() {
     db->lockForRead();
     NSqlQuery query(db);
     qint32 retval = 0;
-    query.exec("Select lid from datastore where key=3007 and data='true'");
+    query.exec("Select lid from datastore where key=3007 and data=1");
     if (query.next()) {
         retval = query.value(0).toInt();
     } else {
@@ -980,9 +980,9 @@ qint32 NotebookTable::getConflictNotebook() {
 int NotebookTable::getNewUnsequencedCount() {
     db->lockForRead();
     NSqlQuery query(db);
-    query.prepare("Select count(lid) from DataStore where key=:key and data=0 and lid not in (select lid from datastore where key=:localkey and data='true')");
+    query.prepare("Select count(lid) from DataStore where key=:key and data=0 and lid not in (select lid from datastore where key=:localkey and data=1)");
     query.bindValue(":key", NOTEBOOK_UPDATE_SEQUENCE_NUMBER);
-    query.bindValue(":localKey", NOTEBOOK_IS_LOCAL);
+    query.bindValue(":localkey", NOTEBOOK_IS_LOCAL);
     query.exec();
     qint32 retval = 0;
     while(query.next()) {
@@ -1000,7 +1000,7 @@ qint32 NotebookTable::getAllDirty(QList<qint32> &lids) {
     NSqlQuery query(db);
     lids.clear();
     db->lockForRead();
-    query.prepare("Select lid from DataStore where key=:key and data='true'");
+    query.prepare("Select lid from DataStore where key=:key and data=1");
     query.bindValue(":key", NOTEBOOK_ISDIRTY);
     query.exec();
     while(query.next()) {
@@ -1127,7 +1127,7 @@ void NotebookTable::closeNotebook(qint32 lid) {
     query.bindValue(":key", NOTEBOOK_IS_CLOSED);
     query.exec();
 
-    query.prepare("insert into DataStore (lid, key, data) values (:lid, :key, 'true')");
+    query.prepare("insert into DataStore (lid, key, data) values (:lid, :key, 1)");
     query.bindValue(":lid", lid);
     query.bindValue(":key", NOTEBOOK_IS_CLOSED);
     query.exec();
diff --git a/sql/notetable.cpp b/sql/notetable.cpp
index 924a38c..6c625ed 100644
--- a/sql/notetable.cpp
+++ b/sql/notetable.cpp
@@ -1104,7 +1104,7 @@ qint32 NoteTable::getIndexNeeded(QList<qint32> &lids) {
     lids.clear();
     qlonglong delayTime = QDateTime::currentDateTime().currentMSecsSinceEpoch()-300000;
     db->lockForRead();
-    query.prepare("Select lid, data from DataStore where key=:key and lid in (select lid from datastore where key=:key2 and data='true')");
+    query.prepare("Select lid, data from DataStore where key=:key and lid in (select lid from datastore where key=:key2 and data=1)");
     query.bindValue(":key", NOTE_UPDATED_DATE);
     query.bindValue(":key2", NOTE_INDEX_NEEDED);
     query.exec();
@@ -1170,7 +1170,7 @@ void NoteTable::updateUrl(qint32 noteLid, QString url, bool setAsDirty=false) {
         query.prepare("Insert into DataStore (lid, key, data) values (:lid, :key, :data)");
         query.bindValue(":lid", noteLid);
         query.bindValue(":key", NOTE_ATTRIBUTE_SOURCE_URL);
-        query.bindValue(":url", url);
+        query.bindValue(":data", url);
         query.exec();
     }
 
@@ -1236,7 +1236,7 @@ void NoteTable::updateAuthor(qint32 noteLid, QString author, bool setAsDirty=fal
     }
 
     query.prepare("Update NoteTable set Author=:author where lid=:lid");
-    query.bindValue(":url", author);
+    query.bindValue(":author", author);
     query.bindValue(":lid", noteLid);
     query.exec();
     query.finish();
@@ -1604,7 +1604,7 @@ qint32 NoteTable::getAllDeleted(QList<qint32> &lids) {
     db->lockForRead();
     lids.clear();
     NSqlQuery query(db);
-    query.prepare("select lid from DataStore where key=:key and data='false'");
+    query.prepare("select lid from DataStore where key=:key and data=0");
     query.bindValue(":key", NOTE_ACTIVE);
     query.exec();
 
@@ -1698,7 +1698,7 @@ void NoteTable::updateNoteContent(qint32 lid, QString content, bool isDirty) {
     query.bindValue(":key", NOTE_CONTENT_LENGTH);
     query.exec();
 
-    query.prepare("update datastore set data='true' where lid=:lid and key=:key");
+    query.prepare("update datastore set data=1 where lid=:lid and key=:key");
     query.bindValue(":lid", lid);
     query.bindValue(":key", NOTE_INDEX_NEEDED);
     query.exec();
@@ -1736,7 +1736,7 @@ qint32 NoteTable::getCount() {
     qint32 retval = 0;
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("Select count(lid) from DataStore where key=:key and lid not in (select lid from datastore where key=:key2 and data = 'true')");
+    query.prepare("Select count(lid) from DataStore where key=:key and lid not in (select lid from datastore where key=:key2 and data = 1)");
     query.bindValue(":key", NOTE_GUID);
     query.bindValue(":key2", NOTE_EXPUNGED_FROM_TRASH);
     query.exec();
@@ -1754,7 +1754,7 @@ qint32 NoteTable::getUnindexedCount() {
     qint32 retval = 0;
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("Select count(lid) from DataStore where key=:key and data='true' and lid not in (select lid from datastore where key=:key2 and data = 'true')");
+    query.prepare("Select count(lid) from DataStore where key=:key and data=1 and lid not in (select lid from datastore where key=:key2 and data = 1)");
     query.bindValue(":key", NOTE_INDEX_NEEDED);
     query.bindValue(":key2", NOTE_EXPUNGED_FROM_TRASH);
     query.exec();
@@ -1866,7 +1866,7 @@ qint32 NoteTable::getAllDirty(QList<qint32> &lids) {
     NSqlQuery query(db);
     db->lockForRead();
     lids.clear();
-    query.prepare("Select lid from DataStore where key=:key and data = 'true'");
+    query.prepare("Select lid from DataStore where key=:key and data = 1");
     query.bindValue(":key", NOTE_ISDIRTY);
     query.exec();
     while(query.next()) {
@@ -1884,7 +1884,7 @@ qint32 NoteTable::getAllDirty(QList<qint32> &lids, qint32 linkedNotebookLid) {
     NSqlQuery query(db);
     lids.clear();
     db->lockForRead();
-    query.prepare("Select lid from DataStore where key=:key and data = 'true' and lid in (select lid from datastore where key=:notebookKey and data=:notebookLid)");
+    query.prepare("Select lid from DataStore where key=:key and data = 1 and lid in (select lid from datastore where key=:notebookKey and data=:notebookLid)");
     query.bindValue(":key", NOTE_ISDIRTY);
     query.bindValue(":notebookKey", NOTE_NOTEBOOK_LID);
     query.bindValue(":notebookLid", linkedNotebookLid);
@@ -1993,7 +1993,7 @@ void NoteTable::reindexAllNotes() {
     query.bindValue(":indexKey", NOTE_INDEX_NEEDED);
     query.exec();
 
-    query.prepare("insert into datastore (lid, key, data) select lid, :indexKey, 'true' from datastore where key=:key;");
+    query.prepare("insert into datastore (lid, key, data) select lid, :indexKey, 1 from datastore where key=:key;");
     query.bindValue(":indexKey", NOTE_INDEX_NEEDED);
     query.bindValue(":key", NOTE_GUID);
     query.exec();
@@ -2129,7 +2129,7 @@ qint32 NoteTable::getNextThumbnailNeeded() {
     qint32 retval = -1;
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("select lid from datastore where data='true' and key=:key limit 1;");
+    query.prepare("select lid from datastore where data=1 and key=:key limit 1;");
     query.bindValue(":key", NOTE_THUMBNAIL_NEEDED);
     query.exec();
     if (query.next()) {
@@ -2146,7 +2146,7 @@ qint32 NoteTable::getThumbnailsNeededCount() {
     qint32 retval = 0;
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("select count(lid)from datastore where data='true' and key=:key;");
+    query.prepare("select count(lid)from datastore where data=1 and key=:key;");
     query.bindValue(":key", NOTE_THUMBNAIL_NEEDED);
     query.exec();
     if (query.next()) {
@@ -2270,7 +2270,7 @@ void NoteTable::pinNote(qint32 lid, bool value) {
     query.exec();
 
     if (!value) {
-        query.prepare("Update NoteTable set isPinned='false' where lid=:lid");
+        query.prepare("Update NoteTable set isPinned=0 where lid=:lid");
         query.bindValue(":lid", lid);
         query.exec();
         QLOG_DEBUG() << query.lastError();
@@ -2278,12 +2278,12 @@ void NoteTable::pinNote(qint32 lid, bool value) {
         return;
     }
 
-    query.prepare("Insert into DataStore (lid, key, data) values (:lid, :key, 'true')");
+    query.prepare("Insert into DataStore (lid, key, data) values (:lid, :key, 1)");
     query.bindValue(":lid", lid);
     query.bindValue(":key", NOTE_ISPINNED);
     query.exec();
 
-    query.prepare("Update NoteTable set isPinned='true' where lid=:lid");
+    query.prepare("Update NoteTable set isPinned=1 where lid=:lid");
     query.bindValue(":lid", lid);
     query.exec();
     query.lastError();
@@ -2312,7 +2312,7 @@ void NoteTable::getAllPinned(QList< QPair< qint32, QString > > &lids) {
     NSqlQuery query(db);
     lids.clear();
     db->lockForRead();
-    query.prepare("Select lid, data from DataStore where key=:titlekey and lid in (select lid from datastore where key=:key and data='true') order by data");
+    query.prepare("Select lid, data from DataStore where key=:titlekey and lid in (select lid from datastore where key=:key and data=1) order by data");
     query.bindValue(":titlekey", NOTE_TITLE);
     query.bindValue(":key", NOTE_ISPINNED);
     query.exec();
diff --git a/sql/nsqlquery.cpp b/sql/nsqlquery.cpp
index a9ab8bc..d570445 100644
--- a/sql/nsqlquery.cpp
+++ b/sql/nsqlquery.cpp
@@ -54,11 +54,23 @@ NSqlQuery::~NSqlQuery() {
 //    }
 }
 
+QString getLastExecutedQuery(const QSqlQuery& query)
+{
+ QString str = query.lastQuery();
+ QMapIterator<QString, QVariant> it(query.boundValues());
+ while (it.hasNext())
+ {
+  it.next();
+  str.replace(it.key(),it.value().toString());
+ }
+ return str;
+}
 
 // Generic exec().  A prepare should have been done already
 bool NSqlQuery::exec() {
     bool indexPauseSave;
     bool indexRestoreNeeded = false;
+    QLOG_DEBUG() << "Sending SQL:" << getLastExecutedQuery(*this);
     for (int i=1; i<1000; i++) {
         bool rc = QSqlQuery::exec();
         if (rc) {
@@ -101,6 +113,7 @@ bool NSqlQuery::exec() {
 bool NSqlQuery::exec(const QString &query) {
     bool indexPauseSave;
     bool indexRestoreNeeded = false;
+    QLOG_DEBUG() << "Sending SQL:" << query;
     for (int i=1; i<1000; i++) {
         bool rc = QSqlQuery::exec(query);
         if (rc) {
@@ -152,7 +165,3 @@ bool NSqlQuery::exec(const char *query) {
     q = QString::fromStdString(query);
     return this->exec(q);
 }
-
-
-
-
diff --git a/sql/resourcetable.cpp b/sql/resourcetable.cpp
index 1d26e26..0b0322f 100644
--- a/sql/resourcetable.cpp
+++ b/sql/resourcetable.cpp
@@ -141,7 +141,7 @@ qint32 ResourceTable::getLid(string resourceGuid) {
 qint32 ResourceTable::getLid(QString resourceGuid) {
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("Select lid from DataStore where key=:key and data=:guid");
+    query.prepare("Select lid from DataStore where key=:key and data=:data");
     query.bindValue(":key", RESOURCE_GUID);
     query.bindValue(":data", resourceGuid);
     query.exec();
@@ -811,7 +811,7 @@ qint32 ResourceTable::getIndexNeeded(QList<qint32> &lids) {
     NSqlQuery query(db);
     lids.clear();
     db->lockForRead();
-    query.prepare("Select lid from DataStore where key=:key and data='true'");
+    query.prepare("Select lid from DataStore where key=:key and data=1");
     query.bindValue(":key", RESOURCE_INDEX_NEEDED);
     query.exec();
     while (query.next()) {
@@ -830,9 +830,9 @@ bool ResourceTable::getResourceList(QList<qint32> &resourceList, qint32 noteLid)
     resourceList.clear();
     db->lockForRead();
     NSqlQuery query(db);
-    query.prepare("Select lid from DataStore where key=:key and data=:notelid");
+    query.prepare("Select lid from DataStore where key=:key and data=:noteLid");
     query.bindValue(":key", RESOURCE_NOTE_LID);
-    query.bindValue(":notelid", noteLid);
+    query.bindValue(":noteLid", noteLid);
     query.exec();
     while (query.next()) {
         int resLid = query.value(0).toInt();
@@ -951,7 +951,7 @@ qint32 ResourceTable::getCount() {
 qint32 ResourceTable::getUnindexedCount() {
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("Select count(lid) from DataStore where key=:key and data='true'");
+    query.prepare("Select count(lid) from DataStore where key=:key and data=1");
     query.bindValue(":key", RESOURCE_INDEX_NEEDED);
     query.exec();
     qint32 retval =0;
@@ -1025,7 +1025,7 @@ void ResourceTable::reindexAllResources() {
     query.bindValue(":indexKey", RESOURCE_INDEX_NEEDED);
     query.exec();
 
-    query.prepare("insert into datastore (lid, key, data) select lid, :indexKey, 'true' from datastore where key=:key;");
+    query.prepare("insert into datastore (lid, key, data) select lid, :indexKey, 1 from datastore where key=:key;");
     query.bindValue(":indexKey", RESOURCE_INDEX_NEEDED);
     query.bindValue(":key", RESOURCE_GUID);
     query.exec();
@@ -1041,7 +1041,7 @@ void ResourceTable::updateNoteLid(qint32 resourceLid, qint32 newNoteLid) {
     db->lockForWrite();
     query.prepare("Update datastore set data=:newNoteLid where lid=:resourceLid and key=:key");
     query.bindValue(":newNoteLid", newNoteLid);
-    query.bindValue(":lid", resourceLid);
+    query.bindValue(":resourceLid", resourceLid);
     query.bindValue(":key", RESOURCE_NOTE_LID);
     query.exec();
     query.finish();
@@ -1074,7 +1074,7 @@ void ResourceTable::getResourceMap(QHash<QString, qint32> &hashMap, QHash<qint32
     NSqlQuery query(db);
     qint32 prevLid = -1;
     db->lockForRead();
-    query.prepare("Select key, data, lid from datastore where lid in (select lid from datastore where key=:key2 and data=:notelid) order by lid");
+    query.prepare("Select key, data, lid from datastore where lid in (select lid from datastore where key=:key2 and data=:noteLid) order by lid");
     query.bindValue(":key2", RESOURCE_NOTE_LID);
     query.bindValue(":noteLid", noteLid);
     query.exec();
@@ -1135,11 +1135,11 @@ void ResourceTable::getAllResources(QList<Resource> &list, qint32 noteLid, bool
     db->lockForRead();
     QHash<qint32, Resource*> lidMap;
     if (fullLoad){
-        query.prepare("Select key, data, lid from datastore where lid in (select lid from datastore where key=:key2 and data=:notelid) order by lid");
+        query.prepare("Select key, data, lid from datastore where lid in (select lid from datastore where key=:key2 and data=:noteLid) order by lid");
         query.bindValue(":key2", RESOURCE_NOTE_LID);
         query.bindValue(":noteLid", noteLid);
     } else {
-        query.prepare("Select key, data, lid from datastore where key=:key and lid in (select lid from datastore where key=:key2 and data=:notelid) order by lid");
+        query.prepare("Select key, data, lid from datastore where key=:key and lid in (select lid from datastore where key=:key2 and data=:noteLid) order by lid");
         query.bindValue(":key", RESOURCE_GUID);
         query.bindValue(":key2", RESOURCE_NOTE_LID);
         query.bindValue(":noteLid", noteLid);
diff --git a/sql/searchtable.cpp b/sql/searchtable.cpp
index 0502c57..6fb9211 100644
--- a/sql/searchtable.cpp
+++ b/sql/searchtable.cpp
@@ -418,7 +418,7 @@ bool SearchTable::update(qint32 lid, SavedSearch &s, bool isDirty=true) {
 bool SearchTable::isDeleted(qint32 lid) {
     NSqlQuery query(db);
     db->lockForRead();
-    query.prepare("Select lid from DataStore where key=:key and lid=:lid and data='true'");
+    query.prepare("Select lid from DataStore where key=:key and lid=:lid and data=1");
     query.bindValue(":lid", lid);
     query.bindValue(":key", SEARCH_ISDELETED);
     query.exec();
@@ -439,7 +439,7 @@ qint32 SearchTable::getAllDirty(QList<qint32> &lids) {
     NSqlQuery query(db);
     lids.clear();
     db->lockForRead();
-    query.prepare("Select lid from DataStore where key=:key and data='true'");
+    query.prepare("Select lid from DataStore where key=:key and data=1");
     query.bindValue(":key", SEARCH_ISDIRTY);
     query.exec();
     while(query.next()) {
diff --git a/sql/sharednotebooktable.cpp b/sql/sharednotebooktable.cpp
index 17ee008..ce87dba 100644
--- a/sql/sharednotebooktable.cpp
+++ b/sql/sharednotebooktable.cpp
@@ -375,7 +375,7 @@ qint32 SharedNotebookTable::findById(qlonglong id) {
     db->lockForRead();
     query.prepare("Select lid from DataStore where key=:key and data=:id");
     query.bindValue(":key", SHAREDNOTEBOOK_ID);
-    query.bindValue(":data", id);
+    query.bindValue(":id", id);
     query.exec();
     if (query.next()) {
         qint32 retval = 0;
@@ -396,7 +396,7 @@ qint32 SharedNotebookTable::findByShareKey(QString id) {
     db->lockForRead();
     query.prepare("Select lid from DataStore where key=:key and data=:id");
     query.bindValue(":key", SHAREDNOTEBOOK_SHARE_KEY);
-    query.bindValue(":data", id);
+    query.bindValue(":id", id);
     query.exec();
     while (query.next()) {
         qint32 retval = query.value(0).toInt();
@@ -423,7 +423,7 @@ qint32 SharedNotebookTable::findByNotebookGuid(QString id) {
     db->lockForRead();
     query.prepare("Select lid from DataStore where key=:key and data=:id");
     query.bindValue(":key", SHAREDNOTEBOOK_NOTEBOOK_GUID);
-    query.bindValue(":data", id);
+    query.bindValue(":id", id);
     query.exec();
     while (query.next()) {
         qint32 retval = query.value(0).toInt();
diff --git a/sql/tagtable.cpp b/sql/tagtable.cpp
index a9f57bd..fd335ab 100644
--- a/sql/tagtable.cpp
+++ b/sql/tagtable.cpp
@@ -608,7 +608,7 @@ qint32 TagTable::getAllDirty(QList<qint32> &lids) {
     NSqlQuery query(db);
     db->lockForRead();
     lids.clear();
-    query.prepare("Select lid from DataStore where key=:key and data='true'");
+    query.prepare("Select lid from DataStore where key=:key and data=1");
     query.bindValue(":key", TAG_ISDIRTY);
     query.exec();
     while(query.next()) {
diff --git a/sql/usertable.cpp b/sql/usertable.cpp
index 5bebbdf..8fabb85 100644
--- a/sql/usertable.cpp
+++ b/sql/usertable.cpp
@@ -101,9 +101,9 @@ void UserTable::createTable() {
 void UserTable::updateUser(User &user) {
     NSqlQuery query(db);
     db->lockForWrite();
-    query.prepare("delete from UserTable where key != :last_date and key != :last_number;");
-    query.bindValue(":key1", USER_SYNC_LAST_DATE);
-    query.bindValue(":key2", USER_SYNC_LAST_NUMBER);
+    query.prepare("delete from UserTable where key != :lastdate and key != :lastnumber;");
+    query.bindValue(":lastdate", USER_SYNC_LAST_DATE);
+    query.bindValue(":lastnumber", USER_SYNC_LAST_NUMBER);
     query.exec();
 
     if (user.id.isSet()) {
diff --git a/threads/counterrunner.cpp b/threads/counterrunner.cpp
index 2e0ec72..769d05f 100644
--- a/threads/counterrunner.cpp
+++ b/threads/counterrunner.cpp
@@ -77,14 +77,14 @@ void CounterRunner::countNotebooks() {
     }
 
     NSqlQuery query(db);
-    query.exec(" select data, count(data) from datastore where key=5011 and lid not in (select lid from datastore where data='false' and key=5010) group by data;");
+    query.exec(" select data, count(data) from datastore where key=5011 and lid not in (select lid from datastore where data=0 and key=5010) group by data;");
     while (query.next()) {
         qint32 lid = query.value(0).toInt();
         qint32 total = query.value(1).toInt();
         allNotebooks[lid] = total;
     }
 
-    query.exec("select notebooklid, count(notebooklid) from notetable where lid in (select lid from filter) and lid not in (select lid from datastore where data='false' and key=5010) group by notebooklid;");
+    query.exec("select notebooklid, count(notebooklid) from notetable where lid in (select lid from filter) and lid not in (select lid from datastore where data=0 and key=5010) group by notebooklid;");
 
     while(query.next()) {
         qint32 lid = query.value(0).toInt();
@@ -115,7 +115,7 @@ void CounterRunner::countTags() {
     }
 
     NSqlQuery query(db);
-    query.exec(" select data, count(data) from datastore where key=5012 and lid not in (select lid from datastore where data='false' and key=5010) group by data;");
+    query.exec(" select data, count(data) from datastore where key=5012 and lid not in (select lid from datastore where data=0 and key=5010) group by data;");
     while (query.next()) {
         qint32 lid = query.value(0).toInt();
         qint32 total = query.value(1).toInt();
@@ -123,7 +123,7 @@ void CounterRunner::countTags() {
     }
 
     // Start counting
-    query.prepare("select data, count(lid) from datastore where key=:key and lid in (select lid from filter) and lid not in (select lid from datastore where data='false' and key=5010) group by data;");
+    query.prepare("select data, count(lid) from datastore where key=:key and lid in (select lid from filter) and lid not in (select lid from datastore where data=0 and key=5010) group by data;");
     query.bindValue(":key", NOTE_TAG_LID);
     query.exec();
     while(query.next()) {
```
PS: I cannot attach text files to this message; I'm bugged off by a message saying that "attaching documents requires write permission to this repository."
PPS: This patch also addresses the bool → 0/1 problem; I'm not sure you want to apply this part, as it seems Qt5 centric, so, sorry it is intertwined with the rest.

**Comment by baumgarr** [comment]
Thanks.  I'll fix the bind values.  The true/false ones I don't want to do because I can't move to Qt5 yet.

Thanks again!

**Comment by michaelcadilhac** [comment]
Maintaining it Qt4/Qt5 does not seem to be a hassle, though.  For the boolean case, you may override bindValue for bool so that it always use the strings "true", "false"; that would ensure backward compatibility of the database. (Although backward compatibility is evil)

**Comment by baumgarr** [comment]
I've pushed out the bind changes.  Hopefully I got them right.  :-)

I'm not sure about what to do with Qt5 yet.  My initial plan was to release
a non-beta NixNote2 with 4.8 for older distros.  Once that was done I'd
migrate to Qt5 for the next major release (maybe 2.1).  That way people who
are stuck on older Qt releases have something usable and I can continue
forward.

If the DB needs updated I'd just set a flag in a config or SQL table that
indicates if it needs to be changed in some way.  In this instance I'd just
update everywhere it says "true/false" to "1/0".  I've learned from the
past that asking people to delete their DB and do a fresh download just
creates confusion.  Half of the people don't do it and then encounter
errors & send emails about problems.

**Comment by michaelcadilhac** [comment]
As far as I can see, you missed `resourcetable.cpp` lines 835 and 1047, `filterengine.cpp` line 797, `sharednotebooktable.cpp:425` and while I'm at it, I need this for attachment to be properly displayed:

```patch
diff --git a/html/attachmenticonbuilder.cpp b/html/attachmenticonbuilder.cpp
index 4fe51d8..6e34a28 100644
--- a/html/attachmenticonbuilder.cpp
+++ b/html/attachmenticonbuilder.cpp
@@ -49,7 +49,8 @@ QString AttachmentIconBuilder::buildIcon(qint32 lid, QString fileName) {
 
     // Setup the font
     QFont font;
-    font.setPointSize (global.defaultGuiFontSize);
+    if (global.defaultGuiFontSize > 0)
+      font.setPointSize (global.defaultGuiFontSize);
     font.setFamily("Arial");
     QFontMetrics fm(font);
     int width =  fm.width(displayName);
```

None of these changes can cause backward incompatibility.  The Qt4→Qt5 diff is minimal, thus there could be some `#ifdef` dealing with the differences if you want to offer the two options.

**Comment by baumgarr** [comment]
Thanks for the double check.

I guess if you want to email me the patch files of everything you've changed I can add the ifdef statements.  That will at least allow you to merge with the main branch, but I'm not going to distribute a Qt5 version until I get a stable one under 4.8.  I don't want to do another set of builds.

**Comment by michaelcadilhac** [comment]
Will do.  Didn't you miss resourcetable.cpp:1041?

**Comment by baumgarr** [comment]
Thanks.

Is doing something like this what you recommend?

#if QT_VERSION >= 0x050000
        sql.prepare("Delete from filter where lid not in (select lid from DataStore where (key=:comp or key=:uncomp) and data=1)");
#else
        sql.prepare("Delete from filter where lid not in (select lid from DataStore where (key=:comp or key=:uncomp) and data='true')");
#endif

**Comment by michaelcadilhac** [comment]
No, this would awfully clutter the code.  You have two options really:

1) Always go with the 0/1 version, by overloading the bindValue
function in Qt4 so that bools are always written with 0/1.  Then,
using a flag in the database, make sure the true/false to 0/1
conversion has been made.

2) Always go with the 'true'/'false' version (which is error prone, as
it's text), in which case you'd overload bindValue in Qt5 so that
bools are always written with 'true'/'false'.

I'd use `#if QT_VERSION`s for the other changes specific to Qt4 → Qt5
(most importantly it seems, the file dialogs).

**Comment by baumgarr** [comment]
I think I have it working.  I've done some quick testing and things look good on 4.8.  I think I've converted everything to 0 & 1 values based on your notes above.  Let me know what I've screwed up.

Thanks.

**Comment by baumgarr** [comment]
I was curious if you could easily test something for me.  I added a printt preview dialog option.  The weird thing is that the preview itself doesn't work properly because it doesn't show any images, but if you do an actual print from the preview dialog it looks correct.  I can't see how this is anything other than a Qt bug, but I was curious if it is fixed in Qt5.  If it doesn't work in Qt5 I'm going to disable this menu option.  It doesn't do much good to have a print preview that isn't previewing properly.

Thanks!

**Comment by baumgarr** [comment]
Ignore my request on the print preview.  I switched from QWebView to TextEdit and the preview works.

Thanks.

**Comment by michaelcadilhac** [comment]
> Let me know what I've screwed up.

Ahah, well :-)  in `nsqlquery.cpp`, the `#endif` is misplaced, but that's all.  The qt4 to qt5 patch is there: http://michael.cadilhac.name/private/nixnote2-qt5.diff
You may want to provide two .pro files, though there may be a better logic.  Also, I did not ship the diff for the autogenerated Makefiles.

Thanks!

**Comment by baumgarr** [comment]
I went through the diff file and merged with the existing Qt4 code.  There were a few places that I still had to do version checks, but a lot of it went in without any issues.  I left Qt4/Qt5 branches around some of the toAscii() / toLatin() and UTF8 logic.  I've run into issues in the past with Qt not displaying non-Latin characters properly.  Does Qt5 handle them differently?

Thanks & let me know what I missed.

**Comment by michaelcadilhac** [comment]
Thanks!  You missed:

```patch
diff --git a/NixNote2.pro b/NixNote2.pro
index 353a277..7dd61c7 100644
--- a/NixNote2.pro
+++ b/NixNote2.pro
@@ -10,7 +10,7 @@ greaterThan(QT_MAJOR_VERSION, 4) {
     INCLUDEPATH += /usr/include/poppler/qt5
     LIBS +=    -lopencv_core -lopencv_highgui -lopencv_imgproc \
                -lhunspell -lcurl \
-           -    lpthread -L/usr/lib -lpoppler-qt5 -g -rdynamic
+               -lpthread -L/usr/lib -lpoppler-qt5 -g -rdynamic
 }
 
 equals(QT_MAJOR_VERSION, 4) {
diff --git a/sql/usertable.h b/sql/usertable.h
index cc2b76d..b7ad59e 100644
--- a/sql/usertable.h
+++ b/sql/usertable.h
@@ -19,6 +19,7 @@ Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
 #ifndef USERTABLE_H
 #define USERTABLE_H
+#include <QtGlobal>
 #if QT_VERSION < 0x050000
 #include <Q_LONG>
 #endif
```
The `#include <QtGlobal>` may also be missing in `qt4helpers.h`, where `QT_VERSION` is referred without previous Qt includes.

**Comment by baumgarr** [comment]
Thanks.  I pushed out the changes.

**Comment by michaelcadilhac** [comment]
As for encoding, I had to simplify your scheme, in particular I don't
get how: `notetable.cpp:191`, which pretty much strips out all UTF8,
works to preserve UTF8 characters.  Removing the conversion there
works like a charm, back and forth.  I'm really unsure why this is
needed in Qt4.

Cheers.

**Comment by baumgarr** [comment]
If everything else is synced with your changes, do you want to push changes directly into the main repository?

**Comment by michaelcadilhac** [comment]
I may want to *commit* changes directly into the main repository :-)
I'm an [xkcd type](xkcd.com/1597) Git user; I understand nothing of
it.  But sure, as long as the Subversion interface works, that could
be helpful!

**Comment by baumgarr** [comment]
You know as much about git as I do.  :-)

I've added you.  I'm going to close this issue.  Feel free to email me directly with any questions or to let me know if I messed something up.

Thanks.
